language: perl
perl:
  - "5.16"
install :
  - cpanm  --quiet -notest Devel::Cover::Report::Coveralls
script :
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
  - cover
after_success :
  - cover -report coveralls
before_install :
  - sudo apt-get install libuuid1 uuid-dev raptor2-utils

