language: perl

sudo: false
addons:
    apt:
        packages:
            - raptor2-utils

perl:
  - "5.16"
  - "5.20"

env:
    - PERL_CPANM_OPT=-n

before_install :
    - cpanm App::cpanoutdated
    - cpan-outdated | cpanm
    - cpanm Devel::Cover Devel::Cover::Report::Coveralls

script :
   - perl Build.PL && ./Build
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine ./Build test
   - cover

cache:
    directories :
        - /home/travis/perl5/perlbrew/perls/5.20/lib/site_perl
        - /home/travis/perl5/perlbrew/perls/5.20/bin
        - /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl
        - /home/travis/perl5/perlbrew/perls/5.16/bin

after_success :
     - cover -report coveralls
